[tool.poetry]
name = "judah"
version = "0.1.0"
description = ""
authors = ["Vincent Horvath <vhorvath2010@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["standard"], version = "^0.115.6"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
